version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "1m"


services:
  nginx:
    <<: *default-opts
    image: nginx
    #container_name: nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
      - com.example.nginx_proxy=true
    ports:
      - target: 443
        published:  443
        mode: host
        protocol: tcp
      - target: 80
        published:  80
        mode: host
        protocol: tcp
    deploy:
      mode: global  # Either global (exactly one container per swarm node) or replicated (a specified number of containers). The default is replicated
      placement:
        constraints: [node.role == manager]
    networks:
      - nginx
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx-gen:
    <<: *default-opts
    image: helder/docker-gen:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true
    command:  -notify  "docker-label-sighup com.example.nginx_proxy" -watch -wait 3s:30s  /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - nginx
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  acme-companion:
    <<: *default-opts
    image: nginxproxy/acme-companion
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      - DEFAULT_EMAIL=tunailgaz@gmail.com
    networks:
      - nginx
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx-conf.d:
    external: true
  nginx-vhost.d:
    external: true
  nginx-html:
    external: true
  nginx-certs:
    external: true
  nginx-htpasswd:
    external: true
  acme:
    external: true



networks:
  nginx:
    external: true


